### ISSUE TITLE
Add support for seaplane

### ISSUE THREAD

**Issue by ijnrghjkdsmigywneig203** [shahzain345/pyppeteer-hcaptcha-solver#1]
Hello, while solving, the seaplane is popping up a lot more and the solver can not solve it. Please add support for the seaplane.

**Comment by shahzain345** [comment]
Sure, will look into it.

**Comment by jindiygnwrgw** [comment]
Hello, hcaptcha added new images and all the images have these purple circles on them. Please try to fix this
